### ISSUE TITLE
Extend background grid

### ISSUE THREAD

**Issue by GlennClatworthy** [comodide/CoModIDE#61] opened 2022-03-21 04:14 UTC
Allow the user to set size parameters for the white background grid. Alternatively, automatically expand the grid to accommodate larger models.

**Comment by hammar** [comment] 2022-04-04 07:35
@cogan-shimizu: there's some interesting stuff in com.mxgraph.swing.mxGraphComponent that we might overload in SchemaDiagramComponent, e.g., the pageFormat, horizontalPageCount, verticalPageCount, and pageBreaksVisible fields. I'm not sure of the best way to front this in the GUI, but if we figure that out, it seems the underlying mechanisms are in place to extend the canvas as requested here.

I don't know whether node son different pages will behave differently w.r.t. folding or other things, we'll have to double-check that.

**Comment by cogan-shimizu** [comment] 2024-05-09 15:26
Duplicate of #15

**Comment by Ambar-Shrivastava** [comment] 2024-05-26 01:54
**Resolution:**
To resolve this issue, we have removed line setPageVisible(true) from class SchemaDiagramComponent.
 
**Below troubleshooting steps has been taken to identify the line of code responsible for having grey area around canvas.**
 
1.        Tried changing the size of graph component using setPreferredSize method.
graphComponent.setPreferredSize(new Dimension (300, 200))
 
This approach did not work, it did not change the size of graph component and have not remove grey space, additionally hardcoding size of graph is not a good solution.
 
2.        Tried to use zoomIn () function for graph component to check if there is possibility of zoom to a predefined scale and if it eliminates grey area.
graphComponent.zoomIn().
 
This approach did not work, and grey area remains intact.
 
3.        Tried to use setScale method to scale of mx graph and its content.
graphComponent.getGraphControl(). setScale(scale)
 
This approach did not work, and grey area remains intact.
 
4.        Tried to change background color of JSplitPane that holds graph component using setBackground function of JPanel.
 
This approach did not work, and grey area remains intact. However, background color of right side of JSplitPane Changed which was holding graph Component.
 
5.        Tried introducing new Jframe to analyze the behavior of graph component separately and tried to change its background color using set Background method of contentPane.
 
This approach did not work, and grey area remains intact.
 
Above steps confirms that grey area was not because of any container that holds graph component, it is the part of graph itself. 
 
6.        As grey area was part of graph component, removed line setPageVisible(true) from class SchemaDiagramComponent
 
This line indeed removed grey area around canvas and now graph occupies all available area.

**Comment by Ambar-Shrivastava** [comment] 2024-05-26 01:59
This Issue is fixed and latest code has been to merged to independent_study_main 
Pull Request #: https://github.com/comodide/CoModIDE/pull/73

**Comment by cogan-shimizu** [comment] 2024-05-26 02:25
Because the issue has not been merged into main, we will leave the issue open.

**Closed** 2024-08-03 02:16 UTC
Labels: bug
